import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f6f5ff",
        "on-primary-fixed-variant": "#00346e",
        "surface-container": "#e3e7ff",
        "on-primary-fixed": "#00102a",
        "outline-variant": "#a1abd7",
        "surface-container-highest": "#d4dbff",
        "on-error": "#ffefee",
        "on-secondary": "#ceffcf",
        "surface-container-high": "#dce1ff",
        "on-secondary-container": "#005723",
        "inverse-primary": "#7cabff",
        "surface-container-lowest": "#ffffff",
        "secondary-dim": "#005d26",
        "inverse-on-surface": "#919bc6",
        "on-surface": "#222d51",
        "on-background": "#222d51",
        "error-container": "#fb5151",
        "secondary": "#006a2c",
        "surface-dim": "#c9d3ff",
        "surface": "#f6f5ff",
        "on-primary": "#eff2ff",
        "on-secondary-fixed": "#004219",
        "surface-bright": "#f6f5ff",
        "surface-container-low": "#eff0ff",
        "on-secondary-fixed-variant": "#006228",
        "error-dim": "#9f0519",
        "tertiary-fixed-dim": "#fe8029",
        "error": "#b31b25",
        "on-tertiary": "#fff0e9",
        "primary-container": "#7cabff",
        "primary-fixed-dim": "#6e9ef1",
        "on-tertiary-container": "#542200",
        "primary-dim": "#0b4e9c",
        "outline": "#6b759e",
        "surface-variant": "#d4dbff",
        "on-primary-container": "#002b5e",
        "on-error-container": "#570008",
        "tertiary": "#974300",
        "primary": "#225aa9",
        "on-surface-variant": "#4f5a81",
        "surface-tint": "#225aa9",
        "tertiary-container": "#ff9656",
        "on-tertiary-fixed-variant": "#612900",
        "secondary-container": "#78f08f",
        "secondary-fixed": "#78f08f",
        "tertiary-dim": "#843a00",
        "secondary-fixed-dim": "#69e182",
        "on-tertiary-fixed": "#2d0f00",
        "tertiary-fixed": "#ff9656",
        "primary-fixed": "#7cabff",
        "inverse-surface": "#000b2f",
      },
      fontFamily: {
        headline: ["var(--font-lexend)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
